# Generated by Django 4.0 on 2021-12-11 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alumini_details_2'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumini',
            name='linkedin',
            field=models.CharField(default='linedkin', max_length=122),
        ),
        migrations.AddField(
            model_name='alumini',
            name='name',
            field=models.CharField(default='name', max_length=100),
        ),
        migrations.AddField(
            model_name='details',
            name='email',
            field=models.CharField(default='email', max_length=122),
        ),
        migrations.AddField(
            model_name='details',
            name='facebook',
            field=models.CharField(default='fb', max_length=122),
        ),
        migrations.AddField(
            model_name='details',
            name='linkedin',
            field=models.CharField(default='linedkin', max_length=122),
        ),
        migrations.AddField(
            model_name='details',
            name='name',
            field=models.CharField(default='name', max_length=200),
        ),
        migrations.AddField(
            model_name='details',
            name='phone',
            field=models.CharField(default='+91', max_length=13),
        ),
        migrations.AddField(
            model_name='details',
            name='post',
            field=models.CharField(default='post', max_length=15),
        ),
        migrations.AddField(
            model_name='details_2',
            name='name',
            field=models.CharField(default='name', max_length=122),
        ),
        migrations.AddField(
            model_name='details_2',
            name='post',
            field=models.CharField(default='member', max_length=15),
        ),
        migrations.AlterField(
            model_name='alumini',
            name='department',
            field=models.CharField(default='civil', max_length=20),
        ),
        migrations.AlterField(
            model_name='alumini',
            name='year',
            field=models.CharField(default=2021, max_length=5),
        ),
    ]
