# Generated by Django 4.0 on 2021-12-11 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alumini_linkedin_alumini_name_details_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='details',
            name='date',
        ),
        migrations.RemoveField(
            model_name='details',
            name='email',
        ),
        migrations.RemoveField(
            model_name='details',
            name='facebook',
        ),
        migrations.RemoveField(
            model_name='details',
            name='linkedin',
        ),
        migrations.RemoveField(
            model_name='details',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='details',
            name='post',
        ),
        migrations.AddField(
            model_name='details',
            name='desc',
            field=models.TextField(default='desc'),
        ),
        migrations.AddField(
            model_name='details',
            name='img',
            field=models.ImageField(default='rec1.jpg', upload_to='pics'),
        ),
        migrations.AddField(
            model_name='details',
            name='offer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='details',
            name='price',
            field=models.IntegerField(default='200'),
        ),
        migrations.AlterField(
            model_name='details',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
