# Generated by Django 4.0 on 2021-12-11 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_remove_details_date_remove_details_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='details',
            name='img',
        ),
        migrations.AlterField(
            model_name='details',
            name='price',
            field=models.IntegerField(default=2020),
        ),
    ]
