# Generated by Django 4.0 on 2021-12-12 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_remove_details_img_alter_details_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='details',
            name='img',
            field=models.ImageField(default='rec1.jpg', upload_to='pics'),
        ),
    ]
