# Generated by Django 4.0 on 2021-12-12 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_details_img'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Alumini',
        ),
        migrations.DeleteModel(
            name='Details_2',
        ),
    ]
