# Generated by Django 4.0 on 2021-12-12 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_delete_alumini_delete_details_2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='details',
            name='offer',
        ),
        migrations.AlterField(
            model_name='details',
            name='price',
            field=models.IntegerField(default=2021),
        ),
    ]
