# Generated by Django 4.0 on 2021-12-12 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_remove_details_offer_alter_details_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='details',
            old_name='price',
            new_name='year',
        ),
        migrations.AlterField(
            model_name='details',
            name='desc',
            field=models.TextField(default='Hey! write here your branch.'),
        ),
    ]
