# Generated by Django 4.0 on 2021-12-12 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_rename_price_details_year_alter_details_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='details',
            name='facebook',
            field=models.CharField(default='www.facebook.com', max_length=200),
        ),
        migrations.AddField(
            model_name='details',
            name='linkedin',
            field=models.CharField(default='www.linkedin.com', max_length=200),
        ),
    ]
